export const initialUnits = [
  {
    id: '1',
    name: 'شقة 3 غرف — كمبوند النيل',
    type: 'شقة',
    area: 'القاهرة الجديدة',
    compound: 'كمبوند النيل',
    price: 2400000,
    size: 180,
    rooms: '3 غرف',
    status: 'متاح',
    lat: 30.044276,
    lng: 31.935553,
    createdAt: new Date('2024-04-01'),
  },
  {
    id: '2',
    name: 'شقة غرفتين - المعادي',
    type: 'شقة',
    area: 'المعادي',
    compound: '',
    price: 1800000,
    size: 110,
    rooms: '2',
    status: 'معلق',
    lat: 29.97,
    lng: 30.93,
    createdAt: new Date('2024-03-15'),
  },
  {
    id: '3',
    name: 'شقة 4 غرف — الهرم',
    type: 'شقة',
    area: ' الهرم',
    compound: 'الهرم',
    price: 1450000,
    size: 170,
    rooms: '4 غرفة',
    status: 'مباع',
    lat: 30.144276,
    lng: 31.539553,
    createdAt: new Date('2024-03-01'),
  },
  {
    id: '4',
    name: 'شقة 3 غرف  — الشيخ زايد',
    type: 'شقة',
    area: 'الشيخ زايد',
    compound: '',
    price: 2200000,
    size: 180,
    rooms: '3 غرف',
    status: 'متاح',
    lat: 30.044276,
    lng: 30.935553,
    createdAt: new Date('2024-02-20'),
  },
];

export const initialMortgageRequests = [
  { id: '1', refNumber: 'TF-2024-089', clientName: 'محمد علي حسن',    amount: 1200000, status: 'موافق عليه',   createdAt: new Date() },
  { id: '2', refNumber: 'TF-2024-090', clientName: 'سارة أحمد محمود', amount: 850000,  status: 'قيد المراجعة', createdAt: new Date() },
  { id: '3', refNumber: 'TF-2024-091', clientName: 'خالد إبراهيم عمر',amount: 3500000, status: 'قيد المراجعة', createdAt: new Date() },
  { id: '4', refNumber: 'TF-2024-092', clientName: 'نور الدين فاروق', amount: 2100000, status: 'مرفوض',        createdAt: new Date() },
];

export const initialClients = [
  { id: '1', name: 'معتز حمدي',  interest: 'مهتم بشقة 3 غرف · القاهرة الجديدة', status: 'عميل نشط',    createdAt: new Date() },
  { id: '2', name: 'هبة منصور',  interest: 'مهتمة بشقة 4 غرف · 6 أكتوبر',      status: 'في المفاوضات', createdAt: new Date() },
  { id: '3', name: 'عمرو طارق',  interest: 'أتم شراء شقة 2 غرف · المعادي',        status: 'مكتمل',        createdAt: new Date() },
];